from openai import OpenAI
from dotenv import load_dotenv
from typing import List
import os
import ast

load_dotenv()

class COTExtractor():
    
    def __init__(self):
        self.model = os.getenv("PROCESSING_MODEL")
        self.prompt_id = os.getenv("COT_PROMPT_ID")
        self.client = OpenAI()
            
    def generate_cot(self, input: str) -> List:
        """
        Generates a response using the model and COT prompt.
        
        Args:
            input (str): The input text/query.
        
        Returns:
            cot_list (str): The list of chain of thought questions generated by the model.
        """
        response = self.client.responses.create(
            model = self.model,
            prompt = {
                "id":self.prompt_id
            },
            input = input
        )
        
        cot_list_string = response.output[0].content[0].text
        cot_list = ast.literal_eval(cot_list_string)
        return cot_list
    
if __name__ == "__main__":
    x = COTExtractor()
    
    question = "What was the trend in Apple stock before, during, and after the Obama administration?"
    y = x.generate_cot(question)
    print(y)